import Head from 'next/head'
import { ReactElement } from 'react'
import Layout from '../components/Layout'
import Navbar from '../components/Navbar'
import SvgArrow from '../components/Icons/arrow-icon'
import Tooltip from '../components/Tooltip'
import ArticleList from '../components/Articles/ArticleList'
import Link from 'next/link'
import { withAuth } from '../HOC/withAuthProvider'

const Home = () => {
  return (
    <>
      <Head>
        <title>Zenn | Homepage</title>
        <meta name='keywords' content='zenn' />
        <meta name='viewport' content='initial-scale=1.0, width=device-width' />
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href='/zenn-favicon.png' />
      </Head>
      <main>
        <section className='bg-main-blue py-14'>
          <div className='mx-auto max-w-[960px] px-[14px] mobile:px-5 tablet:px-[25px] laptop:px-10'>
            <div className='flex items-center'>
              <h1 className='mr-[6px] text-2xl font-bold leading-[1.3] text-primary'>
                Tech
              </h1>
              <Tooltip
                width={140}
                TagName='button'
                label='Knowledge of technology'
              >
                <span className='flex h-[17px] w-[17px] justify-center rounded-[50%] bg-gray-lighter text-[10px] leading-[17px] text-white group-hover:bg-gray-primary'>
                  ?
                </span>
              </Tooltip>
            </div>
            <div className='mt-[1.1rem]'>
              <ArticleList />
            </div>
            <div className='mt-[2.2rem] text-center font-[1.02rem]'>
              <Link
                href='#'
                className='inline-block text-[0.956rem] text-blue-darker hover:underline hover:underline-offset-[0.3em] tablet:text-[1.02rem]'
              >
                More Trending
                <SvgArrow size={16.31} />
              </Link>
            </div>
          </div>
        </section>
        <section className='mt-[2px] bg-main-gray px-0 pt-14 pb-16'>
          <div className='mx-auto max-w-[960px] px-[14px] mobile:px-5 tablet:px-[25px] laptop:px-10'>
            <div className='flex items-center'>
              <h1 className='mr-[6px] text-2xl font-bold leading-[1.3] text-primary'>
                Ideas
              </h1>
              <Tooltip
                width={140}
                TagName='button'
                label='Career, team, work theory, poem, etc.'
              >
                <span className='flex h-[17px] w-[17px] justify-center rounded-[50%] bg-gray-lighter text-[10px] leading-[17px] text-white group-hover:bg-gray-primary'>
                  ?
                </span>
              </Tooltip>
            </div>
            <div className='mt-[1.1rem]'>
              <ArticleList />
            </div>
            <div className='mt-[2.2rem] text-center font-[1.02rem]'>
              <Link
                href='#'
                className='inline-block text-[0.956rem] text-blue-darker hover:underline hover:underline-offset-[0.3em] tablet:text-[1.02rem]'
              >
                More articles
                <SvgArrow size={16.31} />
              </Link>
            </div>
          </div>
        </section>
        <section className='bg-white px-0 pt-14 pb-16'>
          <div className='mx-auto max-w-[960px] px-[14px] mobile:px-5 tablet:px-[25px] laptop:px-10'>
            <div className='flex items-center'>
              <h1 className='text-2xl font-bold leading-[1.3] text-primary'>
                Books
              </h1>
            </div>
            <div className='mt-[2.3rem]'>There is no books yet</div>
          </div>
        </section>
        <section className='mt-4 bg-main-gray py-[3.8rem] px-0'>
          <div className='mx-auto max-w-[960px] px-[14px] mobile:px-5 tablet:px-[25px] laptop:px-10'>
            <div className='flex items-center'>
              <h1 className='text-2xl font-bold leading-[1.3] text-primary'>
                Featured
              </h1>
            </div>
            <div className='mx-0 mt-6 mb-12'>
              <ArticleList />
            </div>
          </div>
        </section>
        {/* {Object.keys(context.auth).length === 0 ? <LoginCta /> : null} */}
      </main>
    </>
  )
}
const HomeWithAuth = withAuth(Home)

const HomeWithLayout = (props: any) => {
  return <HomeWithAuth {...props} />
}

HomeWithLayout.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      <Navbar />
      {page}
      {/* <NestedLayout>{page}</NestedLayout> */}
    </Layout>
  )
}

export default HomeWithLayout
